config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  resources :addresses
  resources :states
  resources :zip_codes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/", to: "addresses#new"

  get "/forecasts/:address_id/forecast", to: "forecasts#forecast"
  get "/forecasts/:address_id/hourly_forecast", to: "forecasts#hourly_forecast"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/zip_code.rb
class ZipCode < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :code,
    length: { is: 5 },
    format: { with: /\A\d{5}\z/,
              message: "must be five digits" }
end

app/controllers/zip_codes_controller.rb
class ZipCodesController < ApplicationController
  before_action :set_zip_code, only: %i[ show edit update destroy ]

  # GET /zip_codes or /zip_codes.json
  def index
    @zip_codes = ZipCode.all
  end

  # GET /zip_codes/1 or /zip_codes/1.json
  def show
  end

  # GET /zip_codes/new
  def new
    @zip_code = ZipCode.new
  end

  # GET /zip_codes/1/edit
  def edit
  end

  # POST /zip_codes or /zip_codes.json
  def create
    @zip_code = ZipCode.new(zip_code_params)

    respond_to do |format|
      if @zip_code.save
        format.html { redirect_to @zip_code, notice: "Zip code was successfully created." }
        format.json { render :show, status: :created, location: @zip_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @zip_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zip_codes/1 or /zip_codes/1.json
  def update
    respond_to do |format|
      if @zip_code.update(zip_code_params)
        format.html { redirect_to @zip_code, notice: "Zip code was successfully updated." }
        format.json { render :show, status: :ok, location: @zip_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zip_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zip_codes/1 or /zip_codes/1.json
  def destroy
    @zip_code.destroy!

    respond_to do |format|
      format.html { redirect_to zip_codes_path, status: :see_other, notice: "Zip code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zip_code
      @zip_code = ZipCode.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def zip_code_params
      params.expect(zip_code: [ :code ])
    end
end

app/helpers/zip_codes_helper.rb
module ZipCodesHelper
end

app/views/zip_codes/_form.html.erb
<%= form_with(model: zip_code) do |form| %>
  <% if zip_code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(zip_code.errors.count, "error") %> prohibited this zip_code from being saved:</h2>

      <ul>
        <% zip_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/zip_codes/_zip_code.html.erb
<div id="<%= dom_id zip_code %>">
  <p>
    <strong>Code:</strong>
    <%= zip_code.code %>
  </p>

</div>

app/views/zip_codes/edit.html.erb
<% content_for :title, "Editing zip code" %>

<h1>Editing zip code</h1>

<%= render "form", zip_code: @zip_code %>

<br>

<div>
  <%= link_to "Show this zip code", @zip_code %> |
  <%= link_to "Back to zip codes", zip_codes_path %>
</div>

app/views/zip_codes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Zip codes" %>

<h1>Zip codes</h1>

<div id="zip_codes">
  <% @zip_codes.each do |zip_code| %>
    <%= render zip_code %>
    <p>
      <%= link_to "Show this zip code", zip_code %>
    </p>
  <% end %>
</div>

<%= link_to "New zip code", new_zip_code_path %>

app/views/zip_codes/new.html.erb
<% content_for :title, "New zip code" %>

<h1>New zip code</h1>

<%= render "form", zip_code: @zip_code %>

<br>

<div>
  <%= link_to "Back to zip codes", zip_codes_path %>
</div>

app/views/zip_codes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @zip_code %>

<div>
  <%= link_to "Edit this zip code", edit_zip_code_path(@zip_code) %> |
  <%= link_to "Back to zip codes", zip_codes_path %>

  <%= button_to "Destroy this zip code", @zip_code, method: :delete %>
</div>