config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  resources :addresses
  resources :states
  resources :zip_codes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/", to: "addresses#new"

  get "/forecasts/:address_id/forecast", to: "forecasts#forecast"
  get "/forecasts/:address_id/hourly_forecast", to: "forecasts#hourly_forecast"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/state.rb
class State < ApplicationRecord
  has_many :addresses, dependent: :destroy

  validates :abbreviation,
    length: { is: 2 },
    format: { with: /\A[A-Z][A-Z]\z/,
              message: "only capital letters are allowed" }

  validates :name, presence: true
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy!

    respond_to do |format|
      format.html { redirect_to states_path, status: :see_other, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.expect(state: [ :abbreviation, :name ])
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :abbreviation, style: "display: block" %>
    <%= form.text_field :abbreviation %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Abbreviation:</strong>
    <%= state.abbreviation %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= state.name %>
  </p>

</div>

app/views/states/edit.html.erb
<% content_for :title, "Editing state" %>

<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "States" %>

<h1>States</h1>

<div id="states">
  <% @states.each do |state| %>
    <%= render state %>
    <p>
      <%= link_to "Show this state", state %>
    </p>
  <% end %>
</div>

<%= link_to "New state", new_state_path %>

app/views/states/new.html.erb
<% content_for :title, "New state" %>

<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>