config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  resources :addresses
  resources :states
  resources :zip_codes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "/", to: "addresses#new"

  get "/forecasts/:address_id/forecast", to: "forecasts#forecast"
  get "/forecasts/:address_id/hourly_forecast", to: "forecasts#hourly_forecast"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]
  before_action :set_zip_code, only: %i[ create update ]
  before_action :load_states

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all.order(id: :desc)
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_path, status: :see_other, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.includes(:state, :zip_code).find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def address_params
      ps = params.expect(address: [ :line_1, :line_2, :city, :state_id ]).
        merge({ zip_code: @zip_code || @address&.zip_code })
      Rails.logger.info("ps: #{ps}")
      ps
    end

    def load_states
      @states = State.all.order(:name)
    end

    def set_zip_code
      Rails.logger.info(params.inspect)
      code = params["address"].delete("zip_code.code")
      Rails.logger.info("code: #{code}")
      @zip_code = code.present? ? ZipCode.find_or_create_by!(code:) : @address&.zip_code
      Rails.logger.info(@zip_code)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Line 1:</strong>
    <%= address.line_1 %>
  </p>

  <p>
    <strong>Line 2:</strong>
    <%= address.line_2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state.name %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= address.zip_code.code %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :line_1, style: "display: block" %>
    <%= form.text_field :line_1 %>
  </div>

  <div>
    <%= form.label :line_2, style: "display: block" %>
    <%= form.text_field :line_2 %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state_id, style: "display: block" %>
    <%= form.select :state_id, @states.map { |state| [state.name, state.id] } %>
  </div>

  <div>
    <%= form.label :"zip_code.code", inner_text: 'Zip code', style: "display: block" %>
    <%= form.text_field :"zip_code.code", value: address&.zip_code&.code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<% content_for :title, "Editing address" %>

<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Addresses" %>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
    <p>
      <%= link_to("Standard forecast",
                  "/forecasts/#{address.id}/forecast") %>
    </p>
    <p>
      <%= link_to('Hourly forecast',
                  "/forecasts/#{address.id}/hourly_forecast") %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<% content_for :title, "New address" %>

<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>